spring:
  rabbitmq:
    username: admin
    password: admin
    host: 47.92.72.146
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true